### ISSUE TITLE
Client validation response issue

### ISSUE THREAD

**Issue by spec-reki** [ZSEIT-Praktyki/Frontend#5]
Good morning,
After some testing I've came across a bug regarding the login and register pages.
This bug is appearing when incorrect input is given into forms.
As a result of this bug border of an input does not behave as it should.
Once given incorrect input it should change color of its border to red, when in reality there is no such change.
I've tried finding the source of this problem, with no results.

**Comment by Infor-Tech** [comment]
Dear spec-reki,
Thank you for your commitment. We will look into this issue and reply to you as fast as we can.

**Comment by Infor-Tech** [comment]
Welcome again,

We are proud to announce, that the issue you have found has been resolved in the latest commit on the main branch of this repository and is no longer an issue. Thanks to your work we could react on this quickly. We are glad that our community wants to improve the experience of using our projects.

Best regards,
Krystian Śliwiński,
Head of some division that does not exists
